### ISSUE TITLE
咨询：为何新建文章，会在articles文件夹下新建html和md，有什么用呢？

### ISSUE THREAD

**Issue by 302wanger** [Moon-Future/vue-node-blog#3]
1. 我尝试删除fs.writeFileSync阻止写入，但无效

**Comment by Moon-Future** [comment]
新建文章时，新建的md文件就是文章内容，因为文本太多，存数据库不太好，所以生成文件，下次修改也是读取这个文件；
新建的html是为了提前生成好html文件，这样在主页浏览这篇文章的时候就只需要读取html文件就可以了，不再浏览时
才去生产




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年4月18日(星期四) 晚上11:22
收件人: "Moon-Future/vue-node-blog"<vue-node-blog@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [Moon-Future/vue-node-blog] 咨询：为何新建文章，会在articles文件夹下新建html和md，有什么用呢？ (#3)



 
我尝试删除fs.writeFileSync阻止写入，但无效

**Comment by 302wanger** [comment]
感谢🙏
